### ISSUE TITLE
Error installing  plugin

### ISSUE THREAD

**Issue by magestik247** [MobileChromeApps/cordova-plugin-chrome-apps-sockets-tcp#1]
I'm trying to install the plugin but always gives me an error, can U tell me what's going on?

Here what I'm get:
Installing "cordova-plugin-chrome-apps-sockets-tcp" for android
Fetching plugin "cordova-plugin-chrome-apps-common@1" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-chrome-apps-common
npm http 404 http://registry.cordova.io/cordova-plugin-chrome-apps-common
Failed to install 'cordova-plugin-chrome-apps-sockets-tcp':Error: 404 Not Found:
 cordova-plugin-chrome-apps-common
    at RegClient.<anonymous> (c:\Users\Jack\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\
lib\request.js:268:14)
    at Request.self.callback (c:\Users\Jack\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:148
:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (c:\Users\Jack\AppData\Roaming\npm\node_modules\cordo
va\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:876:1
4)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (c:\Users\Jack\AppData\Roaming\npm\node_modul
es\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.
js:827:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
Error: 404 Not Found: cordova-plugin-chrome-apps-common
    at RegClient.<anonymous> (c:\Users\Jack\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\
lib\request.js:268:14)
    at Request.self.callback (c:\Users\Jack\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:148
:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (c:\Users\Jack\AppData\Roaming\npm\node_modules\cordo
va\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:876:1
4)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (c:\Users\Jack\AppData\Roaming\npm\node_modul
es\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.
js:827:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by agrieve** [comment]
Looks like your version of cordova is too old. You need v5.0.0 or greater.
